copy /v /y rad_dll\Win32\Release\rad_dll.dll builds
copy /v /y rad_console\Win32\Release\rad_console.exe builds
copy /v /y rad_ui\Win32\Release\rad_ui.exe builds
copy /v /y vs_dll\Release\vs_dll.dll builds
copy /v /y vs_console\Release\vs_console.exe builds
copy /v /y fat32_driver\Win32\Release\fat32_driver.exe builds
copy /v /y sqlite3_console\Win32\Release\sqlite3_console.exe builds
copy /v /y vt_sqlite_ui\Win32\Release\vt_sqlite_ui.exe builds
copy /v /y threaded_drive_rw_ui\Win32\Release\threaded_drive_rw_ui.exe builds
